version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "cd client && npm install && npm run build && cd .. && npm run server & npm run client"
