export enum ErrorMessages {
  UserConflict = "Пользователь с таким именем уже существует",
  UserNotFound = "Пользователь не найден",
  InvalidPassword = "Неверные пароль",
  AccessForbidden = "Доступ запрещен",
  ClassAlreadyAssigned = "Класс уже присвоен пользователю",
  ClassNotFound = "Класс не найден",
  FileNotUploaded = "Не загружен файл",
  ClassNotFoundForVideo = "Занятие не найдено",
  ClassNotAddedToCourse = "Занятие уже добавлено в курс",
  CourseNotFound = "Курс не найден",
  VideoFileNotFound = "Видеофайл не найден",
  FileNotFound = "Файл не найден",
  InvalidRequestBody = "Неверный запрос",
  ServerError = "Ошибка сервера",
  LinkNotAdded = "Ссылка не добавлена",
  CommentNotAdded = "Комментарий не добавлен",
  AccessGranted = "Доступ успешно предоставлен",
  LinkAdded = "Ссылка успешно добавлена",
  Successfully = "Успешно",
}
